# Example configuration for multi-VAE latent precomputation.
#
# Each entry describes a VAE backend along with the resolutions that should
# be encoded. Lists like `[128, 256, 512, 1024, 2048]` are accepted directly.

# Optional global dataset root. Can be overridden via --dataset-root.
dataset_root: datasets/test_dataset

# Base cache directory. If omitted the tool will use
# <dataset_root>/<defaults.cache_subdir>.
cache_root: cache_vae_embeddings

# Settings used when a VAE entry does not override the value.
defaults:
  cache_subdir: cache_embeddings
  variants_per_sample: 1
  batch_size: 512
  num_workers: 8
  resize_long_side: 0
  limit: 0
  store_distribution: true
  device: cuda

# Define the list (or mapping) of VAE backends to precompute.
models:

  # TAESD:
  #   hf_repo: madebyollin/TAESD
  #   weights_dtype: float32
  #   vae_kind: stabble_diffusion_4x
  #   cache_subdir: wan_family
  #   resolutions: [128, 256, 512, 1024]


  sd_vae:
    hf_repo: stabilityai/sd-vae-ft-mse
    weights_dtype: float32
    vae_kind: stabble_diffusion_4x
    cache_subdir: sd_vae
    resolutions_with_batchsize:
      - [128, 512]
      - [256, 224]
      - [512, 100]
      - [1024, 32]

  TAESDXL:
    hf_repo: madebyollin/TAESDXL
    weights_dtype: float32
    vae_kind: stabble_diffusion_4x
    batch_size: 512
    cache_subdir: TAESDXL
    resolutions_with_batchsize:
      - [128, 512]
      - [256, 224]
      - [512, 100]
      - [1024, 32]
