# Baseline single-node configuration. Override values via additional YAML files
# or the CLI --override flag.

ds_path: "./datasets/test_dataset" # test dataset path

project: "simple_latent_solo_model"
save_root_dir: "simple_latent_solo_model"

dataset:
  model_resolution: 64
  high_resolution: 128
  resize_long_side: 1280
  limit: 0
  num_workers: 24
  horizontal_flip_prob: 0.5
  persistent_workers: true

model:
  load_from: ""
  hf_repo: "AuraDiffusion/16ch-vae"
  weights_dtype: "float32"
  mixed_precision: "bf16"
  train_decoder_only: false
  full_training: false
  vae_kind: "kl"  # use "asymmetric_kl" to opt into diffusers.AsymmetricAutoencoderKL
  kl_ratio: 0.0
  use_torch_compile: true
  torch_compile_backend: "inductor"
  torch_compile_mode: "max-autotune"
  torch_compile_fullgraph: false

optimizer:
  batch_size: 90
  base_learning_rate: 1.0
  min_learning_rate: 9e-7
  num_epochs: 750
  optimizer_type: "dadapt_adam"
  beta2: 0.97
  eps: 1e-6
  clip_grad_norm: 1.0
  use_decay: true
  weight_decay: 0.01
  warmup_percent: 0.01
  gradient_accumulation_steps: 4
  scheduler: "cosine"
  cosine_min_ratio: 0.1

loss:
  enabled:
    mae: true
    mse: true
    edge: true
    lpips: true
    ffl: true
    kl: true
    adv: true
  ratios:
    mae: 0.35
    mse: 0.05
    edge: 0.10
    lpips: 0.25
    ffl: 0.15
    kl: 0.0
    adv: 0.10
  median_coeff_steps: 256
  lpips_backbone: "vgg"
  lpips_eval_resolution: 256
  focal_frequency:
    alpha: 1.0
    patch_factor: 1
    log_weight: true
    ave_spectrum: false
    normalize: true
    eps: 1.0e-08

adversarial:
  enabled: false
  loss_type: "ragan"
  update_frequency: 1
  warmup_steps: 1000
  discriminator:
    base_channels: 64
    max_channels: 512
    num_layers: 4
    norm: "instance"
    spectral_norm: true
  optimizer:
    lr: 1.5e-4
    beta1: 0.9
    beta2: 0.99
    weight_decay: 0.0
    clip_grad_norm: 1.0

logging:
  use_wandb: true
  sample_interval_share: 1000
  global_sample_interval: 25
  global_save_interval: 1000
  save_model: true
  save_barrier: 1.003
  log_grad_norm: true

latent_upscaler:
  enabled: true
  width_multiplier: 2
  rrdb_blocks: 8
  growth_channels: 32
  residual_scaling: 0.2

augmentation:
  horizontal_flip_prob: 0.5

ema:
  enabled: false
  decay: 0.999
  update_after_step: 100
  update_interval: 1
