# Comprehensive training configuration for the PixNerf upscaler that exposes
# every option consumed by the streamlined training configuration objects in
# `training/config.py`.

# --- PathsConfig fields ---
project: pixnerf-upscale
save_root_dir: ./runs
# Absolute or relative path to the dataset root.
ds_path: ./unpacked_original_ds/full_dataset
# Optional experiment metadata used when creating the run directory layout.
exp_name: pixnerf-upscale-multiloss
generated_folder_name: samples
seed: 1337

# --- DatasetConfig section ---
dataset:
  high_resolution: 256
  model_resolution: 128
  resize_long_side: 0
  limit: 0
  num_workers: 24

# --- OptimizerConfig section ---
optimizer:
  batch_size: 1024
  base_learning_rate: 0.005
  min_learning_rate: 0.0001
  max_train_steps: 78000
  optimizer_type: adamw
  beta2: 0.99
  eps: 1.0e-08
  clip_grad_norm: 1.0
  use_decay: false
  weight_decay: 0.0
  gradient_accumulation_steps: 1
  scheduler: cosine

# --- ModelConfig section ---
model:
  sample_vaes:
    flux:
      # load_from: ./weights/flux_vae.ckpt
      hf_repo: wolfgangblack/flux_vae
      hf_subfolder: vae
      hf_revision: main
      vae_kind: kl
      weights_dtype: float32
    # sd3_vae_anime_ft:
    #   # load_from: null
    #   hf_repo: Disty0/sd3_vae_anime_ft
    #   hf_revision: main
    #   vae_kind: kl
    #   weights_dtype: float32
  # ostris_vae:
  #   hf_repo: ostris/vae-kl-f8-d16
  #   vae_kind: kl
  #   weights_dtype: float32
  # AuraDiffusion_16ch_vae:
  #   hf_repo: AuraDiffusion/16ch-vae
  #   vae_kind: kl
  #   weights_dtype: float32


# --- LossConfig section ---
loss:
  lpips_backbone: vgg
  components:
    - type: L1Loss
      name: latent_l1
      loss_weight: 1.0
      reduction: mean


# --- LoggingConfig section ---
logging:
  use_wandb: true
  wandb_run_name: pixnerf-upscale
  global_sample_interval: 500
  save_each_n_steps: 3000

# --- LatentUpscalerConfig section ---
latent_upscaler:
  model_name: swin
  window: 8
  depth: 6
  heads: 8
  mlp_ratio: 4.0
  patch_size: 1
  embed_dim: 128
  depths: [6, 6, 6, 6]
  num_heads: [8, 8, 8, 8]
  drop_path_rate: 0.2
  upsampler: pixelshuffle
  load_from: runs/2025_10_09_08_pixnerf-upscale-multiloss/best/

# --- EmbeddingsConfig section ---
embeddings:
  enabled: true
  cache_dir: ./cache_vae_embeddings
  dtype: float32
  overwrite: false
  precompute_batch_size: 64
  precompute_num_workers: 4
  store_distribution: true
  csv_path: ./clear_images_with_embeddings.csv
  vae_names:
    - flux_vae
    # - sd3_vae_anime_ft
    # - AuraDiffusion_16ch_vae
    # - ostris_vae
