# Basic configuration for precomputing latent embeddings compatible with the test dataset.
# dataset_root: /data/kazanplova/datasets/midjourney_full_ds_crops/images/
# cache_root: /data/kazanplova/datasets/midjourney_full_ds_crops/embeddings/
dataset_root: /data/kazanplova/latent_vae_upscale_train/flux_val/256_512/images/
cache_root: /data/kazanplova/latent_vae_upscale_train/flux_val/256_512/embeddings/
# CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 PYTHONPATH="$PWD" accelerate launch --num_processes 6 --main_process_port 29500 scripts/precompute_embeddings.py --config configs/embeddings_precompute.yaml 
defaults:
  num_workers: 64
  embeddings_dtype: float32
  store_distribution: true
  # image_csv: ./clear_images.csv
  devices:
    - cuda:0
    - cuda:1
    # - cuda:2
    # - cuda:3
    # - cuda:4
    # - cuda:5
    # - cuda:6
    # - cuda:7

models:
  sdxl_vae:
    hf_repo: stabilityai/sdxl-vae
    vae_kind: kl
    cache_subdir: sdxl_vae
    resolutions_with_batchsize:
      # - [128, 1024]
      # - [256, 256]
      - [512, 64]